# Generated by Django 5.0.4 on 2024-05-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
