# Generated by Django 5.0.4 on 2024-05-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_to_account'),
    ]

    operations = [
    ]
